map $request_uri $loggable {
    "~^/\\?debugbar"    0;
    "~^/__hot-reload"  0;
    "~^/.well-known/appspecific/com.chrome.devtools.json"  0;
    default            1;
}

server {
    listen 80;
    root /var/www/public;
    index index.php index.html;

    client_max_body_size 50M;

    error_log  /var/log/nginx/error.log error;
    access_log /var/log/nginx/access.log main if=$loggable;

    # Статика (CSS, JS, изображения)
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2|ttf)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        access_log off;
    }

    # Явные пути для CSS и JS
    location /css/ {
        alias /var/www/public/css/;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /js/ {
        alias /var/www/public/js/;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    if ($request_method !~ ^(GET|POST|HEAD)$) {
        return 405;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 600;
        fastcgi_buffering off;
        fastcgi_param PHP_VALUE "display_errors=1";
        fastcgi_param PHP_VALUE "error_reporting=E_ALL";
    }

    add_header X-Robots-Tag "noindex, nofollow" always;
}
